# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdView (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdView (iOS)
  pod 'Google-Mobile-Ads-SDK'


end

target 'AdView (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdView (macOS)

end
